default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
crendentials: &crendentials
  username: postgres
  password: postgres
  host: localhost
  port: 5432

development:
  <<: *default
  <<: *crendentials
  database: coderwall_development

test:
  <<: *default
  <<: *crendentials
  database: coderwall_test

production:
  <<: *default
  database: coderwall_production
