development:
  sessions:
      default:
        database: badgify_development
        hosts:
          - localhost
test:
  sessions:
    default:
      database: badgify_test
      hosts:
        - localhost

staging:
  uri: <%= ENV['MONGOLAB_URI'] %>

production:
  uri: <%= ENV['MONGOLAB_URI'] %>
